spring:
    datasource:
      url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF-8
      username: root
      password: b312030060403
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
       cache: false
       mode: LEGACYHTML5
